package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/componere/incusos-builder/internal/build"
	"github.com/componere/incusos-builder/internal/config"
)

// TestSeedSectionsMatchBuildSeeds asserts the commented seeds list stays in
// sync with every exported [build.Seeds] field.
func TestSeedSectionsMatchBuildSeeds(t *testing.T) {
	t.Parallel()

	typ := reflect.TypeFor[build.Seeds]()
	require.Equal(t, typ.NumField(), len(seedSections), "seedSections must list every build.Seeds field")
	for i := range typ.NumField() {
		field := typ.Field(i)
		require.True(t, field.IsExported(), "build.Seeds field %s must be exported", field.Name)
		require.Equal(t, field.Name, seedSections[i].Field, "seedSections[%d] field", i)
		require.NotEmpty(t, seedSections[i].YAML, "seedSections[%d] yaml name", i)
	}
}

// TestRenderInitConfigNoInputGolden locks the deterministic --no-input example.
func TestRenderInitConfigNoInputGolden(t *testing.T) {
	t.Parallel()

	got := renderInitConfig(exampleInitAnswers(), true)
	want := strings.Join([]string{
		"# Generated by incusos-builder init --no-input.",
		"# Uncommented keys are a valid config; commented seeds list every",
		"# section accepted by this CLI (from build.Seeds YAML names).",
		"#",
		"# image.type: iso | raw",
		"# image.architecture: x86_64 | aarch64",
		"# image.channel: free text; omitted defaults to stable",
		"# image.release: optional exact version pin",
		"# image.offline: true also builds RESCUE_DATA resources media",
		"#",
		"version: 1",
		"image:",
		"  type: iso",
		"  architecture: x86_64",
		"  channel: stable",
		"  offline: false",
		"#seeds:",
		"#  applications: {}",
		"#  incus: {}",
		"#  install: {}",
		"#  migration-manager: {}",
		"#  network: {}",
		"#  operations-center: {}",
		"#  provider: {}",
		"#  services: {}",
		"#  update: {}",
		"#  kernel: {}",
		"#  security: {}",
		"",
	}, "\n")
	require.Equal(t, want, got)
}

// TestRenderInitConfigRoundTripsParse verifies the uncommented body is valid.
func TestRenderInitConfigRoundTripsParse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		answers initAnswers
		noInput bool
	}{
		{name: "example no-input", answers: exampleInitAnswers(), noInput: true},
		{
			name: "interactive raw online",
			answers: initAnswers{
				Type:         build.ImageTypeRaw,
				Architecture: build.ArchAarch64,
				Channel:      "daily",
				Offline:      false,
			},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			body := renderInitConfig(tc.answers, tc.noInput)
			spec, err := config.Parse([]byte(body))
			require.NoError(t, err)
			assert.Equal(t, tc.answers.Type, spec.Type)
			assert.Equal(t, tc.answers.Architecture, spec.Architecture)
			assert.Equal(t, tc.answers.Channel, spec.Channel)
			assert.Equal(t, tc.answers.Offline, spec.Offline)
		})
	}
}

// TestInitNoInputWritesStdout streams the example to -o -.
func TestInitNoInputWritesStdout(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	root := newInitTestCommand(t, &stdout, &stderr, strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", "-"})

	require.NoError(t, root.Execute())
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), stdout.String())
	require.Empty(t, stderr.String())
}

// TestInitNoInputWritesFile writes the example to -o path.
func TestInitNoInputWritesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", path})

	require.NoError(t, root.Execute())
	got, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), string(got))
	require.Empty(t, stdout.String())
}

// TestInitRefusesExistingFile is a usage error (exit 2).
func TestInitRefusesExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	require.NoError(t, os.WriteFile(path, []byte("already here\n"), 0o644))

	root := newInitTestCommand(t, ioDiscard(), ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", path})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	require.Equal(t, exitUsage, exitCode(err))
	require.Contains(t, err.Error(), "refusing to overwrite")
	got, readErr := os.ReadFile(path)
	require.NoError(t, readErr)
	require.Equal(t, "already here\n", string(got))
}

// TestInitJSONEnvelopeWritesOneDocument keeps stdout a single result envelope.
func TestInitJSONEnvelopeWritesOneDocument(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", path})

	require.NoError(t, root.Execute())
	var env initEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, path, env.Result.Output)
	require.Equal(t, 1, strings.Count(stdout.String(), "\n"))
}

// TestInitJSONWithStdoutIsUsage rejects --json -o -.
func TestInitJSONWithStdoutIsUsage(t *testing.T) {
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", "-"})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	var env errorEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, exitUsage, env.Error.Code)
}

// TestInitJSONExistingFileWritesErrorEnvelope keeps stdout one error document.
func TestInitJSONExistingFileWritesErrorEnvelope(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	require.NoError(t, os.WriteFile(path, []byte("already here\n"), 0o644))

	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", path})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	var env errorEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, exitUsage, env.Error.Code)
	require.Contains(t, env.Error.Message, "refusing to overwrite")
}

// TestNewInitFormDoesNotPanic constructs the form (no TTY run).
func TestNewInitFormDoesNotPanic(t *testing.T) {
	t.Parallel()

	answers := exampleInitAnswers()
	channel := string(answers.Channel)
	require.NotPanics(t, func() {
		_ = newInitForm(&answers, &channel)
		_ = initTheme(true)
		_ = initTheme(false)
	})
}

// TestNewInitFormAccessibleDoesNotPanic builds the form with ACCESSIBLE set.
// Huh's accessible prompts each allocate a bufio.Scanner, so a single piped
// script cannot drive every field reliably; full-screen TTY driving is left
// to a later smoke test.
func TestNewInitFormAccessibleDoesNotPanic(t *testing.T) {
	t.Setenv(envAccessible, "1")

	answers := exampleInitAnswers()
	channel := string(answers.Channel)
	require.NotPanics(t, func() {
		form := newInitForm(&answers, &channel).WithAccessible(true)
		require.NotNil(t, form)
	})
}

// newInitTestCommand builds a root+init tree with no-TTY --no-input auto-on.
func newInitTestCommand(t *testing.T, stdout, stderr *bytes.Buffer, stdin *strings.Reader) *cobra.Command {
	t.Helper()
	opts := Options{
		In:        stdin,
		Out:       stdout,
		Err:       stderr,
		Viper:     viper.New(),
		StdinTTY:  func() bool { return false },
		StdoutTTY: func() bool { return false },
	}
	root := NewRootCommand(opts)
	root.AddCommand(newInitCommand(opts))
	return root
}
