package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/componere/incusos-builder/internal/build"
	"github.com/componere/incusos-builder/internal/config"
)

const (
	// envInitSIGINTHelper is set in the re-exec child that waits for SIGINT.
	envInitSIGINTHelper = "INCUSOS_BUILDER_TEST_INIT_SIGINT"
	// envInitSIGINTOutput is the child's -o path.
	envInitSIGINTOutput = "INCUSOS_BUILDER_TEST_INIT_OUT"
)

// TestSeedSectionsMatchBuildSeeds asserts the commented seeds list stays in
// sync with every exported [build.Seeds] field.
func TestSeedSectionsMatchBuildSeeds(t *testing.T) {
	t.Parallel()

	typ := reflect.TypeFor[build.Seeds]()
	sections := seedSections()
	require.Len(t, sections, typ.NumField(), "seedSections must list every build.Seeds field")
	for i := range typ.NumField() {
		field := typ.Field(i)
		require.True(t, field.IsExported(), "build.Seeds field %s must be exported", field.Name)
		require.Equal(t, field.Name, sections[i].Field, "seedSections[%d] field", i)
		require.NotEmpty(t, sections[i].YAML, "seedSections[%d] yaml name", i)
	}
}

// TestRenderInitConfigNoInputGolden locks the deterministic --no-input example.
func TestRenderInitConfigNoInputGolden(t *testing.T) {
	t.Parallel()

	got := renderInitConfig(exampleInitAnswers(), true)
	want := strings.Join([]string{
		"# Generated by incusos-builder init --no-input.",
		"# Uncommented keys are a valid config; commented seeds list every",
		"# section accepted by this CLI (from build.Seeds YAML names).",
		"#",
		"# image.type: iso | raw",
		"# image.architecture: x86_64 | aarch64",
		"# image.channel: free text; omitted defaults to stable",
		"# image.release: optional exact version pin",
		"# image.offline: true also builds RESCUE_DATA resources media",
		"#",
		"version: 1",
		"image:",
		"  type: iso",
		"  architecture: x86_64",
		"  channel: stable",
		"  offline: false",
		"#seeds:",
		"#  applications: {}",
		"#  incus: {}",
		"#  install: {}",
		"#  migration-manager: {}",
		"#  network: {}",
		"#  operations-center: {}",
		"#  provider: {}",
		"#  services: {}",
		"#  update: {}",
		"#  kernel: {}",
		"#  security: {}",
		"",
	}, "\n")
	require.Equal(t, want, got)
}

// TestRenderInitConfigRoundTripsParse verifies the uncommented body is valid.
func TestRenderInitConfigRoundTripsParse(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		answers initAnswers
		noInput bool
	}{
		{name: "example no-input", answers: exampleInitAnswers(), noInput: true},
		{
			name: "interactive raw online",
			answers: initAnswers{
				Type:         build.ImageTypeRaw,
				Architecture: build.ArchAarch64,
				Channel:      "daily",
				Offline:      false,
			},
		},
		{
			name: "interactive offline default application",
			answers: initAnswers{
				Type:         build.ImageTypeISO,
				Architecture: build.ArchX8664,
				Channel:      build.DefaultChannel,
				Offline:      true,
			},
		},
		{
			name: "interactive offline named application",
			answers: initAnswers{
				Type:         build.ImageTypeRaw,
				Architecture: build.ArchAarch64,
				Channel:      "daily",
				Offline:      true,
				Application:  "operations-center",
			},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			body := renderInitConfig(tc.answers, tc.noInput)
			spec, err := config.Parse([]byte(body))
			require.NoError(t, err)
			assert.Equal(t, tc.answers.Type, spec.Type)
			assert.Equal(t, tc.answers.Architecture, spec.Architecture)
			assert.Equal(t, tc.answers.Channel, spec.Channel)
			assert.Equal(t, tc.answers.Offline, spec.Offline)
			if !tc.answers.Offline {
				return
			}
			require.NotNil(t, spec.Seeds.Applications)
			require.NotEmpty(t, spec.Seeds.Applications.Applications)
			wantApp := tc.answers.Application
			if wantApp == "" {
				wantApp = defaultInitApplication
			}
			assert.Equal(t, wantApp, spec.Seeds.Applications.Applications[0].Name)
		})
	}
}

// TestRenderInitConfigFormCombinationsParse validates every type × architecture
// × offline combination the form can emit.
func TestRenderInitConfigFormCombinationsParse(t *testing.T) {
	t.Parallel()

	types := []build.ImageType{build.ImageTypeISO, build.ImageTypeRaw}
	archs := []build.Architecture{build.ArchX8664, build.ArchAarch64}
	offlines := []bool{false, true}
	for _, imageType := range types {
		for _, arch := range archs {
			for _, offline := range offlines {
				answers := initAnswers{
					Type:         imageType,
					Architecture: arch,
					Channel:      build.DefaultChannel,
					Offline:      offline,
					Application:  defaultInitApplication,
				}
				name := fmt.Sprintf("%s_%s_offline-%t", imageType, arch, offline)
				t.Run(name, func(t *testing.T) {
					t.Parallel()
					body := renderInitConfig(answers, false)
					spec, err := config.Parse([]byte(body))
					require.NoError(t, err, "body:\n%s", body)
					assert.Equal(t, answers.Type, spec.Type)
					assert.Equal(t, answers.Architecture, spec.Architecture)
					assert.Equal(t, answers.Channel, spec.Channel)
					assert.Equal(t, answers.Offline, spec.Offline)
					if !offline {
						return
					}
					require.NotNil(t, spec.Seeds.Applications)
					require.Equal(t, defaultInitApplication, spec.Seeds.Applications.Applications[0].Name)
				})
			}
		}
	}
}

// TestInitNoInputWritesStdout streams the example to -o -.
func TestInitNoInputWritesStdout(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	root := newInitTestCommand(t, &stdout, &stderr, strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", "-"})

	require.NoError(t, root.Execute())
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), stdout.String())
	require.Empty(t, stderr.String())
}

// TestInitDotSlashDashIsStdoutNotFile treats ./- as the stdout sentinel.
func TestInitDotSlashDashIsStdoutNotFile(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", "./-"})

	require.NoError(t, root.Execute())
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), stdout.String())
	_, err := os.Stat(filepath.Join(dir, "-"))
	require.ErrorIs(t, err, os.ErrNotExist)
}

// TestInitNoInputWritesFile writes the example to -o path.
func TestInitNoInputWritesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", path})

	require.NoError(t, root.Execute())
	got, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), string(got))
	require.Equal(t, fmt.Sprintf(initWrote+"\n", path), stdout.String())
}

// TestInitQuietSuppressesWroteNotice honors -q after a file write.
func TestInitQuietSuppressesWroteNotice(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-q", "-o", path})

	require.NoError(t, root.Execute())
	got, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), string(got))
	require.Empty(t, stdout.String())
}

// TestInitQuietKeepsJSONEnvelope leaves --json success output intact.
func TestInitQuietKeepsJSONEnvelope(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-q", "--json", "-o", path})

	require.NoError(t, root.Execute())
	var env initEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, path, env.Result.Output)
	require.Equal(t, 1, strings.Count(stdout.String(), "\n"))
}

// TestInitQuietStdoutDashUnaffected still writes the config to stdout.
func TestInitQuietStdoutDashUnaffected(t *testing.T) {
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-q", "-o", "-"})

	require.NoError(t, root.Execute())
	require.Equal(t, renderInitConfig(exampleInitAnswers(), true), stdout.String())
}

// TestInitRefusesExistingFile is a usage error (exit 2).
func TestInitRefusesExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	require.NoError(t, os.WriteFile(path, []byte("already here\n"), 0o644))

	root := newInitTestCommand(t, ioDiscard(), ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "-o", path})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	require.Equal(t, exitUsage, exitCode(err))
	require.Contains(t, err.Error(), "refusing to overwrite")
	got, readErr := os.ReadFile(path)
	require.NoError(t, readErr)
	require.Equal(t, "already here\n", string(got))
}

// TestInitJSONEnvelopeWritesOneDocument keeps stdout a single result envelope.
func TestInitJSONEnvelopeWritesOneDocument(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "out.yaml")
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", path})

	require.NoError(t, root.Execute())
	var env initEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, path, env.Result.Output)
	require.Equal(t, 1, strings.Count(stdout.String(), "\n"))
}

// TestInitJSONWithStdoutIsUsage rejects --json -o -.
func TestInitJSONWithStdoutIsUsage(t *testing.T) {
	testInitJSONStdoutUsage(t, "-")
}

// TestInitJSONWithDotSlashDashIsUsage rejects --json -o ./- as stdout.
func TestInitJSONWithDotSlashDashIsUsage(t *testing.T) {
	testInitJSONStdoutUsage(t, "./-")
}

// testInitJSONStdoutUsage rejects --json with a stdout -o path (exit 2).
func testInitJSONStdoutUsage(t *testing.T, output string) {
	t.Helper()
	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", output})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	var env errorEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, exitUsage, env.Error.Code)
}

// TestInitJSONExistingFileWritesErrorEnvelope keeps stdout one error document.
func TestInitJSONExistingFileWritesErrorEnvelope(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.yaml")
	require.NoError(t, os.WriteFile(path, []byte("already here\n"), 0o644))

	var stdout bytes.Buffer
	root := newInitTestCommand(t, &stdout, ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "--json", "-o", path})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	var env errorEnvelope
	require.NoError(t, json.Unmarshal(stdout.Bytes(), &env))
	require.Equal(t, exitUsage, env.Error.Code)
	require.Contains(t, env.Error.Message, "refusing to overwrite")
}

// TestInitStrayOperandIsUsage is a usage error (exit 2), not an internal exit 1.
func TestInitStrayOperandIsUsage(t *testing.T) {
	root := newInitTestCommand(t, ioDiscard(), ioDiscard(), strings.NewReader(""))
	root.SetArgs([]string{"init", "--no-input", "extra"})

	err := root.Execute()
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	require.Equal(t, exitUsage, exitCode(err))
	require.Contains(t, err.Error(), "accepts no arguments")
}

// TestNewInitFormDoesNotPanic constructs the form (no TTY run).
func TestNewInitFormDoesNotPanic(t *testing.T) {
	t.Parallel()

	answers := exampleInitAnswers()
	channel := string(answers.Channel)
	require.NotPanics(t, func() {
		_ = newInitForm(&answers, &channel)
		_ = initTheme(true)
		_ = initTheme(false)
	})
}

// TestRunInitFormHonorsAccessibleEnv drives runInitForm through the
// project-owned line prompts.
func TestRunInitFormHonorsAccessibleEnv(t *testing.T) {
	t.Setenv(envCI, "")
	t.Setenv(envTerm, "xterm")
	t.Setenv(envAccessible, "1")

	var stderr bytes.Buffer
	answers, err := runInitForm(context.Background(), Options{
		In:  strings.NewReader("2\n2\nnightly\ny\noperations-center\n"),
		Err: &stderr,
	})
	require.NoError(t, err)
	require.Equal(t, build.ImageTypeRaw, answers.Type)
	require.Equal(t, build.ArchAarch64, answers.Architecture)
	require.Equal(t, build.Channel("nightly"), answers.Channel)
	require.True(t, answers.Offline)
	require.Equal(t, "operations-center", answers.Application)
	got := stderr.String()
	require.Contains(t, got, "Enter a number", "accessible select prompt must run")
	require.Contains(t, got, initDescChannel)
	require.Contains(t, got, initDescOffline)
	require.Contains(t, got, initDescApplication)
}

// TestRunInitFormAccessibleEmptyChannelDefaultsStable binds a real Channel default.
func TestRunInitFormAccessibleEmptyChannelDefaultsStable(t *testing.T) {
	t.Setenv(envCI, "")
	t.Setenv(envTerm, "xterm")
	t.Setenv(envAccessible, "1")

	answers, err := runInitForm(context.Background(), Options{
		In:  strings.NewReader("1\n1\n\nn\n"),
		Err: io.Discard,
	})
	require.NoError(t, err)
	require.Equal(t, build.ImageTypeISO, answers.Type)
	require.Equal(t, build.ArchX8664, answers.Architecture)
	require.Equal(t, build.DefaultChannel, answers.Channel)
	require.False(t, answers.Offline)
}

// TestRunInitFormAccessibleEOFCancels treats stdin EOF as init cancelled.
func TestRunInitFormAccessibleEOFCancels(t *testing.T) {
	t.Setenv(envCI, "")
	t.Setenv(envTerm, "xterm")
	t.Setenv(envAccessible, "1")

	_, err := runInitForm(context.Background(), Options{
		In:  strings.NewReader(""),
		Err: io.Discard,
	})
	require.Error(t, err)
	require.True(t, IsUsage(err), "got %v", err)
	require.Equal(t, exitUsage, exitCode(err))
	require.Contains(t, err.Error(), initCancelledMsg)
}

// TestRunInitFormAccessibleContextCancel stops without completing the form.
func TestRunInitFormAccessibleContextCancel(t *testing.T) {
	t.Setenv(envCI, "")
	t.Setenv(envTerm, "xterm")
	t.Setenv(envAccessible, "1")

	reader, writer := io.Pipe()
	t.Cleanup(func() { _ = reader.Close(); _ = writer.Close() })
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	errCh := make(chan error, 1)
	stderr := &safeBuffer{}
	go func() {
		_, err := runInitForm(ctx, Options{In: reader, Err: stderr})
		errCh <- err
	}()

	deadline := time.Now().Add(5 * time.Second)
	for !strings.Contains(stderr.String(), initTitleType) {
		if time.Now().After(deadline) {
			t.Fatalf("timed out waiting for prompt, stderr=%q", stderr.String())
		}
		time.Sleep(20 * time.Millisecond)
	}
	cancel()
	_ = writer.Close()

	select {
	case err := <-errCh:
		require.Error(t, err)
		require.True(t, IsUsage(err), "got %v", err)
		require.Equal(t, exitUsage, exitCode(err))
		require.Contains(t, err.Error(), initCancelledMsg)
	case <-time.After(5 * time.Second):
		t.Fatal("runInitForm did not return after context cancel")
	}
}

// TestInitAccessibleSIGINTExitsUsage sends SIGINT to a child ACCESSIBLE=1 init.
// The child must exit 2 and must not create the output file.
func TestInitAccessibleSIGINTExitsUsage(t *testing.T) {
	if os.Getenv(envInitSIGINTHelper) == "1" {
		runInitAccessibleSIGINTHelper()
		return
	}

	dir := t.TempDir()
	outPath := filepath.Join(dir, "config.yaml")
	ctx, cancel := context.WithTimeout(t.Context(), 15*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, os.Args[0], "-test.run=^TestInitAccessibleSIGINTExitsUsage$")
	cmd.Env = append(os.Environ(),
		envInitSIGINTHelper+"=1",
		envInitSIGINTOutput+"="+outPath,
		envAccessible+"=1",
		envTerm+"=xterm",
		envCI+"=",
		"INCUSOS_BUILDER_NO_INPUT=false",
	)
	stdin, err := cmd.StdinPipe()
	require.NoError(t, err)
	t.Cleanup(func() { _ = stdin.Close() })
	stderrPipe, err := cmd.StderrPipe()
	require.NoError(t, err)
	require.NoError(t, cmd.Start())
	t.Cleanup(func() { _ = cmd.Process.Kill() })

	stderr := &safeBuffer{}
	copyDone := make(chan struct{})
	go func() {
		_, _ = io.Copy(stderr, stderrPipe)
		close(copyDone)
	}()
	waitErr := make(chan error, 1)
	go func() { waitErr <- cmd.Wait() }()

	require.True(t, waitForPrompt(t, stderr, waitErr, initTitleType), "child exited before prompt")
	require.NoError(t, cmd.Process.Signal(os.Interrupt))

	select {
	case err := <-waitErr:
		<-copyDone
		var exitErr *exec.ExitError
		require.ErrorAs(t, err, &exitErr)
		require.Equal(t, exitUsage, exitErr.ExitCode(), "stderr=%s", stderr.String())
	case <-ctx.Done():
		t.Fatalf("timed out waiting for SIGINT exit, stderr=%s", stderr.String())
	}
	_, statErr := os.Stat(outPath)
	require.ErrorIs(t, statErr, os.ErrNotExist)
}

// runInitAccessibleSIGINTHelper is the re-exec child for interactive init.
// It honours process SIGINT via [signal.NotifyContext], matching main.go.
func runInitAccessibleSIGINTHelper() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	root := NewRootCommand(Options{
		In:        os.Stdin,
		Out:       os.Stdout,
		Err:       os.Stderr,
		Viper:     viper.New(),
		StdinTTY:  func() bool { return true },
		StdoutTTY: func() bool { return true },
	})
	root.SetArgs([]string{cmdNameInit, "-o", os.Getenv(envInitSIGINTOutput)})
	err := root.ExecuteContext(ctx)
	stop()
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
	}
	os.Exit(exitCode(err))
}

// safeBuffer is an [io.Writer] that can be read while another goroutine writes.
type safeBuffer struct {
	// mu serializes reads and writes.
	mu sync.Mutex
	// b holds the captured bytes.
	b bytes.Buffer
}

// Write appends p under the mutex.
func (s *safeBuffer) Write(p []byte) (int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.b.Write(p)
}

// String returns the buffer contents under the mutex.
func (s *safeBuffer) String() string {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.b.String()
}

// waitForPrompt reports whether needle appears on stderr before the child exits.
func waitForPrompt(t *testing.T, stderr *safeBuffer, waitErr <-chan error, needle string) bool {
	t.Helper()
	deadline := time.Now().Add(8 * time.Second)
	for {
		if strings.Contains(stderr.String(), needle) {
			return true
		}
		select {
		case err := <-waitErr:
			t.Fatalf("child exited before prompt %q: %v\nstderr=%s", needle, err, stderr.String())
		case <-time.After(20 * time.Millisecond):
		}
		if time.Now().After(deadline) {
			return false
		}
	}
}

// newInitTestCommand builds a root+init tree with no-TTY --no-input auto-on.
func newInitTestCommand(t *testing.T, stdout, stderr *bytes.Buffer, stdin *strings.Reader) *cobra.Command {
	t.Helper()
	opts := Options{
		In:        stdin,
		Out:       stdout,
		Err:       stderr,
		Viper:     viper.New(),
		StdinTTY:  func() bool { return false },
		StdoutTTY: func() bool { return false },
	}
	return NewRootCommand(opts)
}
