// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incusos-builder/internal/build"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRescueWriter creates a new instance of MockRescueWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRescueWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRescueWriter {
	mock := &MockRescueWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRescueWriter is an autogenerated mock type for the RescueWriter type
type MockRescueWriter struct {
	mock.Mock
}

type MockRescueWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRescueWriter) EXPECT() *MockRescueWriter_Expecter {
	return &MockRescueWriter_Expecter{mock: &_m.Mock}
}

// WriteRescue provides a mock function for the type MockRescueWriter
func (_mock *MockRescueWriter) WriteRescue(ctx context.Context, typ build.ImageType, in build.RescueInput, tmpPath string) error {
	ret := _mock.Called(ctx, typ, in, tmpPath)

	if len(ret) == 0 {
		panic("no return value specified for WriteRescue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, build.ImageType, build.RescueInput, string) error); ok {
		r0 = returnFunc(ctx, typ, in, tmpPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRescueWriter_WriteRescue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteRescue'
type MockRescueWriter_WriteRescue_Call struct {
	*mock.Call
}

// WriteRescue is a helper method to define mock.On call
//   - ctx context.Context
//   - typ build.ImageType
//   - in build.RescueInput
//   - tmpPath string
func (_e *MockRescueWriter_Expecter) WriteRescue(ctx any, typ any, in any, tmpPath any) *MockRescueWriter_WriteRescue_Call {
	return &MockRescueWriter_WriteRescue_Call{Call: _e.mock.On("WriteRescue", ctx, typ, in, tmpPath)}
}

func (_c *MockRescueWriter_WriteRescue_Call) Run(run func(ctx context.Context, typ build.ImageType, in build.RescueInput, tmpPath string)) *MockRescueWriter_WriteRescue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 build.ImageType
		if args[1] != nil {
			arg1 = args[1].(build.ImageType)
		}
		var arg2 build.RescueInput
		if args[2] != nil {
			arg2 = args[2].(build.RescueInput)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRescueWriter_WriteRescue_Call) Return(err error) *MockRescueWriter_WriteRescue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRescueWriter_WriteRescue_Call) RunAndReturn(run func(ctx context.Context, typ build.ImageType, in build.RescueInput, tmpPath string) error) *MockRescueWriter_WriteRescue_Call {
	_c.Call.Return(run)
	return _c
}
