// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MockReporter
func (_mock *MockReporter) Done(name string) {
	_mock.Called(name)
	return
}

// MockReporter_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockReporter_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
//   - name string
func (_e *MockReporter_Expecter) Done(name any) *MockReporter_Done_Call {
	return &MockReporter_Done_Call{Call: _e.mock.On("Done", name)}
}

func (_c *MockReporter_Done_Call) Run(run func(name string)) *MockReporter_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporter_Done_Call) Return() *MockReporter_Done_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Done_Call) RunAndReturn(run func(name string)) *MockReporter_Done_Call {
	_c.Run(run)
	return _c
}

// Progress provides a mock function for the type MockReporter
func (_mock *MockReporter) Progress(done int64, total int64) {
	_mock.Called(done, total)
	return
}

// MockReporter_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockReporter_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - done int64
//   - total int64
func (_e *MockReporter_Expecter) Progress(done any, total any) *MockReporter_Progress_Call {
	return &MockReporter_Progress_Call{Call: _e.mock.On("Progress", done, total)}
}

func (_c *MockReporter_Progress_Call) Run(run func(done int64, total int64)) *MockReporter_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReporter_Progress_Call) Return() *MockReporter_Progress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Progress_Call) RunAndReturn(run func(done int64, total int64)) *MockReporter_Progress_Call {
	_c.Run(run)
	return _c
}

// Step provides a mock function for the type MockReporter
func (_mock *MockReporter) Step(name string) {
	_mock.Called(name)
	return
}

// MockReporter_Step_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Step'
type MockReporter_Step_Call struct {
	*mock.Call
}

// Step is a helper method to define mock.On call
//   - name string
func (_e *MockReporter_Expecter) Step(name any) *MockReporter_Step_Call {
	return &MockReporter_Step_Call{Call: _e.mock.On("Step", name)}
}

func (_c *MockReporter_Step_Call) Run(run func(name string)) *MockReporter_Step_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReporter_Step_Call) Return() *MockReporter_Step_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Step_Call) RunAndReturn(run func(name string)) *MockReporter_Step_Call {
	_c.Run(run)
	return _c
}
