// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/componere/incusos-builder/internal/build"
	"github.com/lxc/incus-os/incus-osd/api/images"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageSource creates a new instance of MockImageSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageSource {
	mock := &MockImageSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageSource is an autogenerated mock type for the ImageSource type
type MockImageSource struct {
	mock.Mock
}

type MockImageSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageSource) EXPECT() *MockImageSource_Expecter {
	return &MockImageSource_Expecter{mock: &_m.Mock}
}

// Asset provides a mock function for the type MockImageSource
func (_mock *MockImageSource) Asset(ctx context.Context, version string, file images.UpdateFile) (build.VerifiedAsset, error) {
	ret := _mock.Called(ctx, version, file)

	if len(ret) == 0 {
		panic("no return value specified for Asset")
	}

	var r0 build.VerifiedAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, images.UpdateFile) (build.VerifiedAsset, error)); ok {
		return returnFunc(ctx, version, file)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, images.UpdateFile) build.VerifiedAsset); ok {
		r0 = returnFunc(ctx, version, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(build.VerifiedAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, images.UpdateFile) error); ok {
		r1 = returnFunc(ctx, version, file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageSource_Asset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Asset'
type MockImageSource_Asset_Call struct {
	*mock.Call
}

// Asset is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - file images.UpdateFile
func (_e *MockImageSource_Expecter) Asset(ctx any, version any, file any) *MockImageSource_Asset_Call {
	return &MockImageSource_Asset_Call{Call: _e.mock.On("Asset", ctx, version, file)}
}

func (_c *MockImageSource_Asset_Call) Run(run func(ctx context.Context, version string, file images.UpdateFile)) *MockImageSource_Asset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 images.UpdateFile
		if args[2] != nil {
			arg2 = args[2].(images.UpdateFile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageSource_Asset_Call) Return(verifiedAsset build.VerifiedAsset, err error) *MockImageSource_Asset_Call {
	_c.Call.Return(verifiedAsset, err)
	return _c
}

func (_c *MockImageSource_Asset_Call) RunAndReturn(run func(ctx context.Context, version string, file images.UpdateFile) (build.VerifiedAsset, error)) *MockImageSource_Asset_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type MockImageSource
func (_mock *MockImageSource) Index(ctx context.Context) (images.Index, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 images.Index
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (images.Index, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) images.Index); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(images.Index)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageSource_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockImageSource_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockImageSource_Expecter) Index(ctx any) *MockImageSource_Index_Call {
	return &MockImageSource_Index_Call{Call: _e.mock.On("Index", ctx)}
}

func (_c *MockImageSource_Index_Call) Run(run func(ctx context.Context)) *MockImageSource_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageSource_Index_Call) Return(index images.Index, err error) *MockImageSource_Index_Call {
	_c.Call.Return(index, err)
	return _c
}

func (_c *MockImageSource_Index_Call) RunAndReturn(run func(ctx context.Context) (images.Index, error)) *MockImageSource_Index_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseMetadata provides a mock function for the type MockImageSource
func (_mock *MockImageSource) ReleaseMetadata(ctx context.Context, version string, selected []images.UpdateFile) (build.ReleaseMetadata, error) {
	ret := _mock.Called(ctx, version, selected)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseMetadata")
	}

	var r0 build.ReleaseMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []images.UpdateFile) (build.ReleaseMetadata, error)); ok {
		return returnFunc(ctx, version, selected)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []images.UpdateFile) build.ReleaseMetadata); ok {
		r0 = returnFunc(ctx, version, selected)
	} else {
		r0 = ret.Get(0).(build.ReleaseMetadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []images.UpdateFile) error); ok {
		r1 = returnFunc(ctx, version, selected)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageSource_ReleaseMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseMetadata'
type MockImageSource_ReleaseMetadata_Call struct {
	*mock.Call
}

// ReleaseMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
//   - selected []images.UpdateFile
func (_e *MockImageSource_Expecter) ReleaseMetadata(ctx any, version any, selected any) *MockImageSource_ReleaseMetadata_Call {
	return &MockImageSource_ReleaseMetadata_Call{Call: _e.mock.On("ReleaseMetadata", ctx, version, selected)}
}

func (_c *MockImageSource_ReleaseMetadata_Call) Run(run func(ctx context.Context, version string, selected []images.UpdateFile)) *MockImageSource_ReleaseMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []images.UpdateFile
		if args[2] != nil {
			arg2 = args[2].([]images.UpdateFile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageSource_ReleaseMetadata_Call) Return(releaseMetadata build.ReleaseMetadata, err error) *MockImageSource_ReleaseMetadata_Call {
	_c.Call.Return(releaseMetadata, err)
	return _c
}

func (_c *MockImageSource_ReleaseMetadata_Call) RunAndReturn(run func(ctx context.Context, version string, selected []images.UpdateFile) (build.ReleaseMetadata, error)) *MockImageSource_ReleaseMetadata_Call {
	_c.Call.Return(run)
	return _c
}
