// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifiedAsset creates a new instance of MockVerifiedAsset. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifiedAsset(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifiedAsset {
	mock := &MockVerifiedAsset{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifiedAsset is an autogenerated mock type for the VerifiedAsset type
type MockVerifiedAsset struct {
	mock.Mock
}

type MockVerifiedAsset_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifiedAsset) EXPECT() *MockVerifiedAsset_Expecter {
	return &MockVerifiedAsset_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockVerifiedAsset
func (_mock *MockVerifiedAsset) Open(ctx context.Context) (io.ReadCloser, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (io.ReadCloser, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) io.ReadCloser); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifiedAsset_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockVerifiedAsset_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVerifiedAsset_Expecter) Open(ctx any) *MockVerifiedAsset_Open_Call {
	return &MockVerifiedAsset_Open_Call{Call: _e.mock.On("Open", ctx)}
}

func (_c *MockVerifiedAsset_Open_Call) Run(run func(ctx context.Context)) *MockVerifiedAsset_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVerifiedAsset_Open_Call) Return(readCloser io.ReadCloser, err error) *MockVerifiedAsset_Open_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockVerifiedAsset_Open_Call) RunAndReturn(run func(ctx context.Context) (io.ReadCloser, error)) *MockVerifiedAsset_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockVerifiedAsset
func (_mock *MockVerifiedAsset) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockVerifiedAsset_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockVerifiedAsset_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockVerifiedAsset_Expecter) Size() *MockVerifiedAsset_Size_Call {
	return &MockVerifiedAsset_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockVerifiedAsset_Size_Call) Run(run func()) *MockVerifiedAsset_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVerifiedAsset_Size_Call) Return(n int64) *MockVerifiedAsset_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockVerifiedAsset_Size_Call) RunAndReturn(run func() int64) *MockVerifiedAsset_Size_Call {
	_c.Call.Return(run)
	return _c
}
